# transport method, support `shm` and `rdma` for now
# comm_type = "rdma"
comm_type = "shm"

# listener socket for rdma handshake
# server thread #N will listen on <port> + N
receiver_socket = "127.0.0.1:8002"
device_name = "mlx5_1"
device_port = 1

# channel name for server and client to find each other, the name strings are not matter
daemon_socket = "127.0.0.1:8001"
stoc_channel_name = "/stoc"
ctos_channel_name = "/ctos"

# buffer size
buf_size = 4000000000

# network configuration
# bandwidth is in bps, rtt is in ms 
rtt = 0.0
bandwidth = 77491947438.08
